name: 'package'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  package:
    name: 'Package'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags
      - name: Capture Yarn cache path
        id: yarn-cache-folder
        run: echo "YARN_CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-folder.outputs.YARN_CACHE_FOLDER }}
          key: yarn-cache
      - name: Install dependencies
        run: tool/yarn install --frozen-lockfile
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Package
        run: tool/yarn package
      - name: Upload vsix artifact
        uses: actions/upload-artifact@v3
        with:
          name: vsix
          path: '*.vsix'
