name: 'package'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  package:
    name: 'Package'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags
      - name: Capture Yarn cache path
        id: yarn-cache-folder
        run: echo "YARN_CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Yarn cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-folder.outputs.YARN_CACHE_FOLDER }}
          key: yarn-cache
      - name: Install dependencies
        run: tool/yarn install --frozen-lockfile
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: '1.25.x'
      - name: Capture version
        id: version
        run: npm run env | grep npm_package_version >> $GITHUB_OUTPUT
      - name: Package
        run: tool/yarn package
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.version.outputs.npm_package_version }}
      - name: Upload vsix artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: vsix
          path: '*.vsix'
